import type { Metadata } from "next";
import { Roboto, Fira_Code, Source_Code_Pro } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});
const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${firaCode.variable} ${sourceCodePro.variable} antialiased`}
      >
        <header className="fixed top-[0px] w-full h-[7rem] backdrop-blur-[2px] border border-black text-lg font-[family-name:var(--font-source-code-pro)]">
        <nav className="w-full h-full flex flex-wrap justify-between items-center border border-white">
          <div className="flex border border-black ml-2">
            Leonel Subelza
          </div>
          <div className="w-[50%] flex justify-between items-center border border-black">
            <ul className="w-full flex flex-wrap justify-evenly items-center mx-3 border border-black">
              <li className="flex justify-center items-center">
                <a href="/#">Home</a>
              </li>
              <li>
                <a href="/#projects">Projects</a>
              </li>
              <li>
                <a href="/#contact">Contact</a>
              </li>
            </ul>
            <div className="w-[30%] flex flex-wrap justify-between items-center border border-black">
              <button>Dark/Light</button>
              <select name="select">
                <option value="value1">Spanish</option>
                <option value="value3">English</option>
              </select>
            </div>
          </div>
        </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
